#!/usr/bin/env bash

for feature in ps1 git rbenv atom jenv ivy-cli k8s profile wsl-keychain; do
    if [ -f ~/.dotfiles/dotfiles-$feature ]; then
        source ~/.dotfiles/dotfiles-$feature
    fi
done
