#!/usr/bin/env bash

kube() {
    ruby -e "$(cat <<RUBY
def kube_pos
  result = %x[kubectl get po -n #{ARGV[0]}]
  puts result
end

def run
  case ARGV.shift
  when "po"; kube_po
  when "pos"; kube_pos
  when "exec"; kube_exec
  else; help
  end
end
run
RUBY
)
" "$@"
}

kubens() {
    kubectl config get-contexts | grep "*" | awk '{ print $5 }'
}