#!/usr/bin/env bash

. ~/.git-completion.bash
. ~/.git-prompt.sh
. ~/.git-flow-completion.bash

export PS1='@\h:\w $(__git_ps1 "(%s)")\n\$ '

export GIT_EDITOR=vim

if [ -n "`which hub`" ]; then
    eval "$(hub alias -s)"
fi
