#!/usr/bin/env bash

for feature in  ps1 \
                git \
                k8s-context \
                asdf \
                rbenv \
                atom \
                jenv \
                ivy-cli \
                shimmer \
                k8s \
                wsl-keychain \
                wslprofile \
                profile; do
    if [ -f ~/.dotfiles/dotfiles-$feature ]; then
        source ~/.dotfiles/dotfiles-$feature
    fi
done
