#!/usr/bin/env bash

if [ -f ~/.dotfiles/dotfiles-git ]; then
    . ~/.dotfiles/dotfiles-git
fi

if [ -f ~/.dotfiles/dotfiles-rbenv ]; then
    . ~/.dotfiles/dotfiles-rbenv
fi

if [ -f ~/.dotfiles/dotfiles-atom ]; then
    . ~/.dotfiles/dotfiles-atom
fi

if [ -f ~/.dotfiles/dotfiles-java ]; then
    . ~/.dotfiles/dotfiles-java
fi

if [ -f ~/.dotfiles/dotfiles-jenv ]; then
    . ~/.dotfiles/dotfiles-jenv
fi

if [ -f ~/.dotfiles/dotfiles-ivy-cli ]; then
    . ~/.dotfiles/dotfiles-ivy-cli
fi
