#!/usr/bin/env bash

kubepo() {
    kubectl get po -n $1 | grep $2 | awk '{ print $1 }' | head -n 1
}

kubepos() {
    if [ -z "$2" ]; then
        kubectl get po -n $1
    else
        kubectl get po -n $1 | grep $2
    fi
}

kubeexec() {
    kubectl exec -it -n $1 $(kubepo $1 $2) $3
}

kube() {
    ruby -e <<EOF "$@"
puts ARGV
EOF
}

kubens() {
    kubectl config get-contexts | grep "*" | awk '{ print $5 }'
}