#!/usr/bin/env bash

export LIQUIBASE_HOME=~/.java/liquibase-3.2.2-bin
export M2_HOME=~/.java/apache-maven-3.2.3
export M2=$M2_HOME/bin
export PATH=$PATH:$LIQUIBASE_HOME:$M2:~/.java/activator-1.2.10-minimal
