#!/usr/bin/env bash
# Usage: dotfiles install <feature>

set -e

function features() {
  pushd $_DOTFILES_ROOT/.. 1> /dev/null
  set +e
  ls dotfiles/dotfiles-* 2> /dev/null | sed $'s/dotfiles\/dotfiles-//'
  set -e
  popd 1> /dev/null
}

# Provide dotfiles completions
if [ "$1" = "--complete" ]; then
  echo 'dotfiles'
  features
  exit
fi

function install() {
  local feature=$1
  if [ -z "$feature" ]; then
    dotfiles help install
    exit
  fi

  local result
  set +e
  features | grep $feature > /dev/null
  result=$?
  set -e
  if [ $result -eq 0 ]; then
    install_feature $feature
  else
    case $feature in
    dotfiles)
      install_bash_profile
      update_dotfiles
      ;;
    *)
      dotfiles help install
      ;;
    esac
  fi
}

function install_feature() {
  local feature=$1
  shift

  if [ -f $_DOTFILES_ROOT/libexec/dotfiles-$feature ]; then
    echo Calling dotfiles $feature to prep for install...
    dotfiles $feature prep $*
  fi

  local feature_config_dir=$_DOTFILES_ROOT/../$feature
  if [ -d $feature_config_dir ]; then
    for file in $(ls $feature_config_dir); do
      cp $feature_config_dir/$file ~/.$file
    done
  fi

  local feature_init_file=$_DOTFILES_ROOT/../dotfiles/dotfiles-$feature
  if [ -f $feature_init_file ]; then
    cp $feature_init_file ~/.dotfiles
  fi

  update_dotfiles
}

function install_bash_profile() {
  local profile_filename
  if [ -f ~/.bash_profile ]; then
    profile_filename=~/.bash_profile
  else
    profile_filename=~/.bashrc
  fi

  cat <<-BASHRC >> $profile_filename
### Added by dotfiles install dotfiles
if [ -f ~/.dotfiles/dotfiles ]; then
    source ~/.dotfiles/dotfiles
fi
BASHRC
}

function update_dotfiles() {
  dotfiles update
}

install $*
