#!/usr/bin/env bash
# Usage: dotfiles git prep

# Provide dotfiles completions
if [ "$1" = "--complete" ]; then
    echo prep
    exit
fi

GIT_COMPLETTION_URL="https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash"
GIT_PROMPT_URL="https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh"

function git-run() {
    command=$1
    case $command in
        prep)
            curl -o git/git-completion.bash $GIT_COMPLETTION_URL
            curl -o git/git-prompt.sh $GIT_PROMPT_URL
            ;;
        *)
            exec dotfiles help git ;;
    esac
}

git-run $1
