#!/usr/bin/env bash
# Usage: dotfiles install <feature>

set -e

function features() {
  ls dotfiles/dotfiles-* | sed $'s/dotfiles\/dotfiles-//'
}

# Provide dotfiles completions
#if ARGV.first == "--complete"
if [ "$1" = "--complete" ]; then
  echo 'dotfiles'
  features
  exit
fi

function install() {
  local feature=$1
  if [ -z "$feature" ]; then
    dotfiles help install
    exit
  fi

  local result
  set +e
  $(features | grep $feature)
  result=$?
  set -e
  if [ $result -eq 0 ]; then
    install_feature $feature
  else
    case $feature in
    dotfiles)
      install_bash_profile
      update_dotfiles
      ;;
    *)
      dotfiles help install
      ;;
    esac
  fi
}

function install_feature() {
  echo gonna install $1
}

function install_bash_profile() {
  echo gonna install bash_profile
}

function update_dotfiles() {
  echo gonna update dotfiles
}

# def install feature = :help, *args
#   if FEATURES.include?(feature)
#     install_feature feature, *args
#   else
#     case feature
#     when 'dotfiles'
#       install_bash_profile
#       update_dotfiles
#     else
#       exec 'dotfiles help install'
#     end
#   end
# end

# def install_feature feature_name, *args
#   if File.exists?("sub/libexec/dotfiles-#{feature_name}")
#     puts "Calling dotfiles #{feature_name} to prep for install..."
#     system "dotfiles #{feature_name} prep #{args.join(' ')}"
#   end

#   if Dir.exists? feature_name
#     Dir.chdir feature_name do
#       Dir['**'].each do |file_name|
#         %x(cp #{file_name} ~/.#{file_name})
#       end
#     end
#   end

#   if File.exists? "dotfiles/dotfiles-#{feature_name}"
#     %x(cp dotfiles/dotfiles-#{feature_name} ~/.dotfiles)
#   end
#   update_dotfiles
# end

# def update_dotfiles
#   # copy dotfiles index so anything recently added gets taken into consideration
#   %x(dotfiles update)
# end

# def install_bash_profile
#   bash_profile = File.expand_path('~/.bash_profile')
#   unless File.exist? bash_profile
#     bash_profile = File.expand_path('~/.bashrc')
#   end

#   File.open bash_profile, 'a' do |file|
#     file.puts
#     file.puts "### Added by dotfiles-install"
#     file.puts 'if [ -f ~/.dotfiles/dotfiles ]; then'
#     file.puts '    . ~/.dotfiles/dotfiles'
#     file.puts 'fi'
#   end
# end

# install *ARGV
install $*
