#!/usr/bin/env bash
# Usage: dotfiles update
# Summary: Update the sourced dotfiles hierarchy when installing a new feature.

function dotfiles-update() {
    if [ ! -d ~/.dotfiles ]; then
        echo "Creating .dotfiles directory..."
        mkdir ~/.dotfiles
    fi

    cp dotfiles/dotfiles ~/.dotfiles/dotfiles
}

dotfiles-update
